Tinh: Tinh.o hinhVuong.o tron.o tamgiac.o
	gcc -o Tinh Tinh.o hinhVuong.o tron.o tamgiac.o -lm
Tinh.o: Tinh.c hinhVuong.h tron.h tamgiac.h
	gcc -c Tinh.c 
hinhVuong.o: hinhVuong.c hinhVuong.h
	gcc -c hinhVuong.c
tamgiac.o: tamgiac.c tamgiac.h
	gcc -c tamgiac.c
tron.o: tron.c tron.h
	gcc -c tron.c
	
